Nav 61 markdown to html
fjelltopp/navigator_engine pull request #20
Opened 2021-11-11 13:44 UTC by jsoppela

2021-11-11 17:19 UTC, jonathansberry requested changes
Small change for you to clock.  Checking if a cell of any type is nan is a problem pandas has nicely solved for us.  Otherwise let's get it merged.

2021-11-11 17:19 UTC, jonathansberry commented on navigator_engine/common/graph_loader.py
> +            return None
I think you can replace this with the more concise:
```suggestion
    if pd.isnull(md_in):
            return None
```

2021-11-12 06:05 UTC, jsoppela commented
I've tested that the suggested change with `pd.isnull()` works. The problem with `np.isnan()` was that it raises an exception if the input parameter is a string.

2021-11-12 08:45 UTC, jonathansberry approved these changes

2021-11-12 09:01 UTC, merged