NAV-57 Add action checklist endpoint
fjelltopp/navigator_engine pull request #51
Opened 2021-11-23 01:28 UTC by jonathansberry

This PR adds an action checklist endpoint. 

At this time the checklist only covers actions in the action breadcrumbs from calling decide.  Further work may be done later to forecast future actions that will need to be completed.  

See line 187+ of `test_endpoints.py` for an example response showing how I'm proposing the checklist is is structured.

2021-11-23 08:50 UTC, tomeksabala reviewed
I have one comment which I'd like to talk about before getting this merged in.

2021-11-23 08:50 UTC, tomeksabala commented on navigator_engine/api.py
> +    if engine.stop_action and engine.stop_action != engine.decision['id']:
That's a little misleading. We're including the current decision id in the breadcrumbs. So calling decide with `stopAction = breadcrumbs[-1]['id]` should return a valid decision IMO. What do you think?
I have send exactly this request yesterday and after getting error "The actionID is not in the action path" I thought it's an engine bug.

2021-11-23 10:29 UTC, tomeksabala approved these changes

2021-11-24 07:14 UTC, tomeksabala commented on navigator_engine/tests/integration_tests/test_endpoints.py
> +            'complete': True,
shoudn't "complete" be renamed to "terminus"?

2021-11-24 10:38 UTC, tomeksabala requested changes
It was agreed to change the edpoint to `/api/action/list`
Example response:
```
{
  "milestones": [
    {"id", "title", "progress"}
  ],
  "actions": [
    {"id", "milestoneID":  <nullable>, "title", "skipped", "reached", "manualConfirmationRequired"}

  ]
}
```

2021-11-24 19:19 UTC, jonathansberry commented
This is replacef by https://github.com/fjelltopp/navigator_engine/pull/55

2021-11-24 19:19 UTC, closed without merging