Nav 140 zipped csv data loader
fjelltopp/navigator_engine pull request #52
Opened 2021-11-23 15:24 UTC by jsoppela

2021-11-24 12:04 UTC, jonathansberry requested changes
Hi Jyri,  Great job starting this.  As you understand more about engine my comments below will likely make more sense.  We are using the data you have loaded to check whether the user can proceed to the next step of their workflow.  If the data legitimately doesn't exist, we should to fail silently here and leave it so that those checks can flag the missing data to the user. If the data is bad/corrupted/wrongly defined then we should raise errors here.

2021-11-24 12:04 UTC, jonathansberry commented on navigator_engine/tests/unit_tests/test_data_loaders.py
> +def test_load_csv_from_zipped_resource(mock_engine, mocker):
ideally we would have some tests that asserts an empty response is still raised if there is no archive file, or archive file is missing a csv file matching the reg ex.

2021-11-24 14:04 UTC, jsoppela commented on navigator_engine/pluggable_logic/data_loaders.py
> +    return dataframe
Where is `data[resource_type]['url']` defined?

2021-11-25 09:09 UTC, jonathansberry requested changes
It was probably my fault for not articulating what I was after clearly enough.  I've just made some suggestions to show precisely what I was thinking.  You should check you understand them and commit them, check the tests pass, before I merge.

2021-11-25 09:09 UTC, jonathansberry commented on navigator_engine/pluggable_logic/data_loaders.py
> +                dataframe = pd.read_csv(csv_file)
```suggestion
            elif len(matching_filenames) == 0:
                dataframe = None
            else:
                with zip_file.open(matching_filenames[0], 'r') as csv_file:
                    dataframe = pd.read_csv(csv_file)
```

2021-11-25 09:09 UTC, jonathansberry commented on navigator_engine/pluggable_logic/data_loaders.py
> +        return data
IOError is the wrong error for me to raise.  I will fix this in a later PR. Also, as I mentioned in my last comment I think the assumption should be that data[resource_type] could be empty. Not that an error gets thrown.  I think I need to fix this also in a later PR. Would suggest the following...

```suggestion
    data = load_estimates_dataset_resource(resource_type, auth_header, engine)
    if not data[resource_type]['data']:
        data[name] = {
            'data': None,
            'auth_header': None,
            'url': None
        }
        return data
```

2021-11-25 09:11 UTC, jonathansberry commented on navigator_engine/tests/unit_tests/test_data_loaders.py
> +                'auth_header': 'Bearer xxxx-xxxx-xxxx-xxxx',
In CKAN's case it is not a bearer token.  I would just get rid of Bearer, although admittedly it's only a cosmetic change for readbility.

2021-11-25 09:11 UTC, jonathansberry commented on navigator_engine/tests/unit_tests/test_data_loaders.py
> +        return_value={'spectrum-file': {'data': spectrum_file}}
This is done :+1:

2021-11-25 09:30 UTC, jonathansberry requested changes
Just some more changes.

2021-11-25 09:30 UTC, jonathansberry commented on navigator_engine/pluggable_logic/data_loaders.py
> +
```suggestion

    del data[resource_type]
    
```

2021-11-25 09:30 UTC, jonathansberry commented on navigator_engine/tests/unit_tests/test_data_loaders.py
> +        side_effect=IOError()
Need to mock out empty file not IO Error

2021-11-25 14:08 UTC, jonathansberry approved these changes

2021-11-25 14:08 UTC, merged